version: 2
jobs:
  build:
    working_directory: ~/NotifyExtSubscriber
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: mongo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node
      - image: mongo
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master

deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
            - attach_workspace:
                at: /tmp/workspace
            - run: echo $SERVICE_ACCOUNT > ~/service-account.json
            - run: gcloud auth activate-service-account --key-file ~/service-account.json
            - run: gcloud config set project frivillighetsportalen-1084
            - run: gsutil cp /tmp/workspace/deploy/startup.sh gs://notifyextsubscriber-service/
            - run: gsutil cp /tmp/workspace/app.tar.gz gs://notifyextsubscriber-service/
            - run: 'gcloud compute instance-groups list-instances notifyextsubscriber-group-1 --zone europe-west1-b | tail -n +2 | grep -o "^\S*" | xargs -L1 gcloud compute instances reset --zone europe-west1-b'
